version: "3"

services:
  database:
    build: ./database
    container_name: database
    restart: always
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - spring_net
    image: anhpvhe/full-stack-userdashboard-database

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database
    image: anhpvhe/full-stack-userdashboard-backend

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - frontend_net
    image: anhpvhe/full-stack-userdashboard-frontend

networks:
  spring_net:
  frontend_net:

volumes:
  database_data:
